Repository mdsreq-fga-unb/2024.2-T01-CRMProInjecao, pull requests merged in 2024-12, with the labels that each got.

#42 docs: update segmentacao-do-cliente
  docs/cenario-atual.md
Labels: product and project vision

#49 Doc/44 engenharia de requisitos
  docs/engenharia-requisitos.md
  mkdocs.yml
Labels: product and project vision

#51 Hotfix/50 readme
  .gitignore
  README.md
Labels: product and project vision

#54 Doc/45 lista requisitos
  docs/requisitos-software.md
  mkdocs.yml
Labels: product and project vision

#59 atualização de cargos dos membros da equipe (docs)
  README.md
  assets/home.html
Labels: product and project vision

#58 atualização de cargos dos membros da equipe (main)
  README.md
Labels: product and project vision

#52 Adiciona seção ao documento para identificar causas não resolvíveis apenas com software
  docs/solucao-proposta.md
Labels: improvement

#61 ci: removing unused ci
  .github/workflows/docs.yml
Labels: ci

#57 Doc/47 dor dod
  docs/dor-dod.md
  mkdocs.yml
Labels: product and project vision

#63 Doc/62 estrategias esw
  docs/engenharia-requisitos.md
  docs/estrategias-de-engenharia-de-software.md
Labels: product and project vision

#65 docs: updating backlog
  docs/product-backlog.md
Labels: product and project vision

#70 Doc/69 interacao equipe cliente
  assets/home.html
  docs/interacao-equipe-cliente.md
Labels: product and project vision
