Repository mdsreq-fga-unb/2024.2-T01-CRMProInjecao, pull requests merged in 2024-11, with the labels that each got.

#6 docs: updating fabio infos
  README.md
Labels: documentation

#3 CI for docs
  .github/workflows/docs.yml
Labels: ci

#13 docs: updating readme
  README.md
Labels: documentation

#16 14 nova versao da primeira parte
  docs/cenario-atual.md
  docs/solucao-proposta.md
Labels: documentation

#18 ci: moving ci to docs branch
  .github/workflows/docs.yml
  docs/index.md
Labels: bug, ci

#15 7 33 justificativa
  docs/css/main.css
  docs/estrategias-de-engenharia-de-software.md
  mkdocs.yml
Labels: documentation

#19 docs: Creating and adding text to interacao-entre-equipe-e-cliente
  docs/interacao-entre-equipe-e-cliente.md
Labels: documentation

#23 docs: adicao da comunicacao/validacao
  docs/interacao-entre-equipe-e-cliente.md
Labels: documentation

#20 4 cronograma e entregas
  README.md
  docs/cronograma-de-entregas.md
Labels: documentation

#22 docs: creating licoes aprendidas
  docs/licoes-aprendidas.md
Labels: documentation

#25 docs: adding meet link
  docs/apresentacao-1.md
  mkdocs.yml
Labels: documentation

#27 Feature/ajustes documentacao
  assets/home.html
  assets/images/apple-touch-icon.png
  assets/images/favicon.ico
  assets/images/favicon.png
  assets/images/illustration.webp
  assets/images/logo-vetor.png
  assets/javascripts/iconsearch_index.json
  assets/javascripts/main.js
  assets/javascripts/removeCredits.js
  assets/javascripts/termynal.js
  assets/plugins/__init__.py
  assets/plugins/group/__init__.py
  assets/plugins/group/config.py
  assets/plugins/group/plugin.py
  assets/plugins/info/__init__.py
  assets/plugins/info/config.py
  assets/plugins/info/patterns.py
  assets/plugins/info/plugin.py
  assets/plugins/search/__init__.py
  assets/plugins/search/config.py
  assets/plugins/search/plugin.py
  assets/plugins/tags/__init__.py
  assets/plugins/tags/config.py
  assets/plugins/tags/plugin.py
  assets/stylesheets/extra.css
  docs/assets/images/apple-touch-icon.png
  docs/assets/images/favicon.ico
  docs/assets/images/favicon.png
  docs/assets/images/illustration.webp
  docs/assets/images/logo-vetor.png
  docs/assets/javascripts/custom.4e50d00f.min.js
  docs/assets/javascripts/custom.4e50d00f.min.js.map
  docs/assets/javascripts/iconsearch_index.json
  docs/assets/javascripts/removeCredits.js
  docs/assets/javascripts/termynal.js
  docs/guia-contribuicao/code_of_conduct.md
  docs/guia-contribuicao/politica_de_branchs.md
  docs/guia-contribuicao/politica_de_commits.md
  docs/index.md
  mkdocs.yml
  requirements.txt
Labels: product and project vision, enhancement

#37 docs: change in delivery schedule and sprints
  docs/cronograma-de-entregas.md
Labels: product and project vision

#36 docs: add theoric references in the software engineering strategies document
  docs/estrategias-de-engenharia-de-software.md
  docs/guia-contribuicao/politica_de_commits.md
Labels: product and project vision

#38 Doc/32 cenario atual
  docs/assets/fish-bone.png
  docs/assets/images/fish-bone.png
  docs/cenario-atual.md
Labels: product and project vision
