Repository mdsreq-fga-unb/2024.2-T01-CRMProInjecao, pull requests merged in 2025-01, with the labels that each got.

#83 docs: updating backlog
  docs/product-backlog.md
Labels: product and project vision

#87 Update product-backlog
  docs/product-backlog.md
Labels: product and project vision, improvement

#90 Update engenharia-requisitos
  docs/engenharia-requisitos.md
Labels: product and project vision, improvement, requirements

#91 Consulta de Clientes por filtro
  .env.example
  db/data-source.ts
  ormconfig.json
  src/app.module.ts
  src/auth/auth.service.ts
  src/client/client.controller.spec.ts
  src/client/client.controller.ts
  src/client/client.module.ts
  src/client/client.service.spec.ts
  src/client/client.service.ts
  src/client/dto/create-client.dto.ts
  src/client/dto/search-client.dto.ts
  src/client/dto/update-client.dto.ts
  src/client/entities/client.entity.ts
  src/user/entities/user.entity.ts
  src/vehicle/dto/create-vehicle.dto.ts
  src/vehicle/dto/update-vehicle.dto.ts
  src/vehicle/entities/vehicle.entity.ts
  src/vehicle/vehicle.controller.spec.ts
  src/vehicle/vehicle.controller.ts
  src/vehicle/vehicle.module.ts
  src/vehicle/vehicle.service.spec.ts
  src/vehicle/vehicle.service.ts
Labels: enhancement

#93 Doc/92 estudo de caso usm
  docs/assets/images/aluno.png
  docs/assets/images/coordenador-pedagogico.png
  docs/assets/images/especialisatas-externos.png
  docs/assets/images/pais.png
  docs/assets/images/professor-coordenador.png
  docs/assets/images/professor-participante.png
  docs/estudo-de-caso-usm.md
  mkdocs.yml
Labels: product and project vision

#96 03 Atualizar e desativar clientes
  .env.example
  src/client/client.controller.ts
  src/client/client.service.ts
  src/client/dto/update-client.dto.ts
Labels: enhancement

#98 Update licoes-aprendidas
  docs/licoes-aprendidas.md
Labels: product and project vision

#99 Doc/94 estudo de caso pbb
  docs/assets/images/ana-a-diretora-de-operacoes.png
  docs/assets/images/carlos-tecnico-de-campo.png
  docs/assets/images/expectativas.png
  docs/assets/images/mariana-a-atendente.png
  docs/assets/images/problemas.png
  docs/assets/images/rafale-o-cliente-coorporativo.png
  docs/estudo-de-caso-pbb.md
  mkdocs.yml
Labels: product and project vision

#97 73 lista de requisitos funcionais
  docs/product-backlog.md
  docs/requisitos-software.md
Labels: product and project vision

#101 docs: adding video 3
  docs/apresentacao-3.md
  mkdocs.yml
Labels: product and project vision

#120 Doc/105 pbb bdd
  .env.example
  .gitignore
  Makefile
  docs/assets/images/ana-a-diretora-de-operacoes.png
  docs/assets/images/carlos-tecnico-de-campo.png
  docs/assets/images/expectativas.png
  docs/assets/images/imagens-pbb/expectativas.png
  docs/assets/images/imagens-pbb/persona-1.png
  docs/assets/images/imagens-pbb/persona-2.png
  docs/assets/images/imagens-pbb/persona-3.png
  docs/assets/images/imagens-pbb/persona-4.png
  docs/assets/images/imagens-pbb/problemas.png
  docs/assets/images/mariana-a-atendente.png
  docs/assets/images/problemas.png
  docs/assets/images/rafale-o-cliente-coorporativo.png
  docs/estudo-de-caso-pbb.md
  docs/estudo-de-caso-pbb/bdd.md
  docs/estudo-de-caso-pbb/criterios-aceitacao.md
  docs/estudo-de-caso-pbb/estudo-de-caso-pbb.md
  docs/estudo-de-caso-pbb/lista-historias-usuario.md
  docs/estudo-de-caso-pbb/problemas-identificados.md
  mkdocs.yml
Labels: product and project vision

#110 Documentation: 109-unidade3-video
  docs/apresentacao-3.md
Labels: bug, improvement

#121 feat(products): add initial products module with basic create functio…
  src/app.module.ts
  src/products/dto/create-product.dto.ts
  src/products/dto/update-product.dto.ts
  src/products/entities/category.entity.ts
  src/products/entities/product.entity.ts
  src/products/products.controller.spec.ts
  src/products/products.controller.ts
  src/products/products.module.ts
  src/products/products.service.spec.ts
  src/products/products.service.ts
  src/vehicle/vehicle.service.ts
  test/jest-e2e.json
Labels: API
