Repository mdsreq-fga-unb/2024.2-T01-CRMProInjecao, pull requests merged in 2025-02, with the labels that each got.

#127 improve(reset-password): pages added
  src/api/user.ts
  src/app/auth/forgot-password/layout.tsx
  src/app/auth/forgot-password/page.tsx
  src/app/auth/new-password/[id]/layout.tsx
  src/app/auth/new-password/[id]/page.tsx
  src/app/dashboard/users/loading.tsx
  src/app/dashboard/users/page.tsx
  src/layouts/dashboard/config-navigation.tsx
  src/routes/paths.ts
  src/sections/auth-demo/classic/classic-forgot-password-view.tsx
  src/sections/auth-demo/classic/classic-new-password-view.tsx
  src/sections/auth-demo/classic/classic-verify-view.tsx
  src/sections/auth-demo/classic/index.ts
  src/sections/auth-demo/modern/modern-login-view.tsx
  src/sections/user/user-new-edit-form.tsx
  src/sections/user/user-table-filters-result.tsx
  src/sections/user/user-table-row.tsx
  src/sections/user/user-table-toolbar.tsx
  src/sections/user/view/user-list-view.tsx
  src/types/user.ts
  src/utils/axios.ts
Labels: enhancement, FRONT-END

#126 Feat/22-23
  .env.example
  db/data-source.ts
  nest-cli.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/email/email.controller.spec.ts
  src/email/email.controller.ts
  src/email/email.module.ts
  src/email/email.service.spec.ts
  src/email/email.service.ts
  src/email/templates/simpleEmail.hbs
  src/email/templates/templates.types.ts
  src/token/dto/create-token.dto.ts
  src/token/dto/edit-token.dto.ts
  src/token/entities/token.entity.ts
  src/token/token.module.ts
  src/token/token.service.spec.ts
  src/token/token.service.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.module.ts
  src/user/user.service.ts
  yarn.lock
Labels: enhancement, API

#136 Feat back/feedback
  src/app.module.ts
  src/auth/auth.service.ts
  src/client/client.service.ts
  src/client/entities/client.entity.ts
  src/feedback/dto/create-feedback.dto.ts
  src/feedback/dto/update-feedback.dto.ts
  src/feedback/entities/feedback.entity.ts
  src/feedback/feedback.controller.spec.ts
  src/feedback/feedback.controller.ts
  src/feedback/feedback.module.ts
  src/feedback/feedback.service.spec.ts
  src/feedback/feedback.service.ts
  src/products/products.controller.ts
  src/products/products.service.ts
  src/service-order/entities/budget.entity.ts
  src/service-order/service-order.controller.ts
  src/vehicle/vehicle.controller.spec.ts
  src/vehicle/vehicle.service.spec.ts
Labels: enhancement, API

#137 improve(service-order,feedback): complete crud pages, with simple fil…
  src/api/budget.ts
  src/api/feedback.ts
  src/api/product.ts
  src/api/service-order.ts
  src/app/dashboard/feedbacks/page.tsx
  src/app/dashboard/service-orders/page.tsx
  src/layouts/dashboard/config-navigation.tsx
  src/routes/paths.ts
  src/sections/feedback/feedback-client-form.tsx
  src/sections/feedback/feedback-new-edit-form.tsx
  src/sections/feedback/feedback-table-filters-result.tsx
  src/sections/feedback/feedback-table-row.tsx
  src/sections/feedback/feedback-table-toolbar.tsx
  src/sections/feedback/view/feedback-list-view.tsx
  src/sections/service-order/service-order-new-edit-form.tsx
  src/sections/service-order/service-order-table-filters-result.tsx
  src/sections/service-order/service-order-table-row.tsx
  src/sections/service-order/service-order-table-toolbar.tsx
  src/sections/service-order/service-order-type-modal.tsx
  src/sections/service-order/service-order-type-new-edit-form.tsx
  src/sections/service-order/view/service-order-list-view.tsx
  src/sections/user/view/user-list-view.tsx
  src/types/budget.ts
  src/types/category.ts
  src/types/feedback.ts
  src/types/product.ts
  src/types/service-order.ts
  src/utils/axios.ts
Labels: enhancement, FRONT-END

#123 Vinculação das US com as sprints correspondentes
  docs/cronograma-entregas.md
Labels: product and project vision

#139 Feature api/13 consultar produtos filtros
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/category/category.controller.spec.ts
  src/category/category.controller.ts
  src/category/category.module.ts
  src/category/category.service.spec.ts
  src/category/category.service.ts
  src/category/dto/create-category.dto.ts
  src/category/dto/update-category.dto.ts
  src/category/entities/category.entity.ts
  src/client/client.service.ts
  src/client/entities/client.entity.ts
  src/email/email.controller.spec.ts
  src/email/email.controller.ts
  src/email/email.module.ts
  src/email/email.service.spec.ts
  src/email/email.service.ts
  src/email/templates/templates.types.ts
  src/feedback/dto/create-feedback.dto.ts
  src/feedback/entities/feedback.entity.ts
  src/feedback/feedback.controller.ts
  src/feedback/feedback.module.ts
  src/feedback/feedback.service.spec.ts
  src/feedback/feedback.service.ts
  src/products/entities/product.entity.ts
  src/products/products.module.ts
  src/products/products.service.spec.ts
  src/products/products.service.ts
  src/service-order/budget.controller.ts
  src/service-order/budget.service.ts
  src/service-order/dto/create-budget.dto.ts
  src/service-order/dto/create-service-order-type.dto.ts
  src/service-order/dto/create-service-order.dto.ts
  src/service-order/dto/update-budget.dto.ts
  src/service-order/dto/update-service-order-type.dto.ts
  src/service-order/entities/budget.entity.ts
  src/service-order/entities/service-order.entity.ts
  src/service-order/service-order.controller.ts
  src/service-order/service-order.module.ts
  src/service-order/service-order.service.spec.ts
  src/service-order/service-order.service.ts
  src/token/dto/create-token.dto.ts
  src/token/dto/edit-token.dto.ts
  src/token/entities/token.entity.ts
  src/token/token.module.ts
  src/token/token.service.spec.ts
  src/token/token.service.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.spec.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/vehicle/vehicle.controller.spec.ts
  src/vehicle/vehicle.service.spec.ts
  test/mocks/mock.factory.ts
Labels: API

#135 131-docs/estudo-de-caso-uc/template-especificacao-caso-de-uso
  docs/estudo-de-caso-uc/template-especificacao-caso-de-uso.md
  mkdocs.yml
Labels: product and project vision

#141 Doc/140 atualizando template
  docs/estudo-de-caso-uc/caso-de-uso-01.md
  docs/estudo-de-caso-uc/introducao.md
  mkdocs.yml
Labels: product and project vision

#142 Add caso-de-uso-02.md
  docs/estudo-de-caso-uc/caso-de-uso-02.md
  docs/estudo-de-caso-uc/introducao.md
  mkdocs.yml
Labels: product and project vision

#147 Update cronograma-entregas.md
  docs/cronograma-entregas.md
Labels: product and project vision

#146 add licoes aprendidas unidade 4
  docs/licoes-aprendidas.md
Labels: product and project vision

#156 Feat back/service feedback complements
  src/email/email.controller.spec.ts
  src/email/email.service.spec.ts
  src/feedback/feedback.controller.ts
  src/feedback/feedback.service.spec.ts
  src/feedback/feedback.service.ts
  src/products/products.service.ts
  src/service-order/budget.service.ts
  src/service-order/dto/create-budget.dto.ts
  src/service-order/dto/update-service-order.dto.ts
  src/service-order/entities/budget.entity.ts
  src/service-order/entities/service-history.entity.ts
  src/service-order/entities/service-order.entity.ts
  src/service-order/service-history.controller.ts
  src/service-order/service-history.service.ts
  src/service-order/service-order.controller.ts
  src/service-order/service-order.module.ts
  src/service-order/service-order.service.spec.ts
  src/service-order/service-order.service.ts
  src/service-order/service-stats.controller.ts
  src/service-order/service-stats.service.ts
  src/user/dto/create-user.dto.ts
  src/user/user.controller.spec.ts
Labels: enhancement, improvement, API

#154 Feat front/service feedback complements
  package.json
  src/api/budget.ts
  src/api/category.ts
  src/api/feedback.ts
  src/api/service-history.ts
  src/api/service-order.ts
  src/api/service-stats.ts
  src/api/user.ts
  src/app/dashboard/budgets/page.tsx
  src/app/dashboard/services/budgets/[id]/page.tsx
  src/app/dashboard/services/budgets/new/page.tsx
  src/app/dashboard/services/budgets/page.tsx
  src/app/dashboard/services/orders/[id]/page.tsx
  src/app/dashboard/services/orders/new/page.tsx
  src/app/dashboard/services/orders/page.tsx
  src/app/dashboard/services/overview/page.tsx
  src/app/feedback/layout.tsx
  src/app/feedback/page.tsx
  src/components/chart/index.tsx
  src/components/service-history/service-history-timeline.tsx
  src/layouts/dashboard/config-navigation.tsx
  src/routes/paths.ts
  src/sections/budget/budget-new-edit-form.tsx
  src/sections/budget/budget-table-filters-result.tsx
  src/sections/budget/budget-table-row.tsx
  src/sections/budget/budget-table-toolbar.tsx
  src/sections/budget/view/budget-create-view.tsx
  src/sections/budget/view/budget-details-view.tsx
  src/sections/budget/view/budget-list-view.tsx
  src/sections/budget/view/index.ts
  src/sections/feedback/feedback-client-form.tsx
  src/sections/feedback/feedback-new-edit-form.tsx
  src/sections/feedback/view/feedback-list-view.tsx
  src/sections/product/product-new-edit-form.tsx
  src/sections/product/view/product-list-view.tsx
  src/sections/service-order/service-order-new-edit-form.tsx
  src/sections/service-order/service-order-table-filters-result.tsx
  src/sections/service-order/service-order-table-row.tsx
  src/sections/service-order/service-order-table-toolbar.tsx
  src/sections/service-order/service-order-type-modal.tsx
  src/sections/service-order/view/index.ts
  src/sections/service-order/view/service-order-create-view.tsx
  src/sections/service-order/view/service-order-details-view.tsx
  src/sections/service-order/view/service-order-list-view.tsx
  src/sections/services/recent-services.tsx
  src/sections/services/service-create-dialog.tsx
  src/sections/services/service-stats.tsx
  src/sections/services/service-status-chart.tsx
  src/sections/services/view/services-overview.tsx
  src/sections/user/user-new-edit-form.tsx
  src/sections/user/user-table-row.tsx
  src/sections/user/view/user-list-view.tsx
  src/theme/next-emotion-cache.tsx
  src/types/budget.ts
  src/types/service-history.ts
  src/types/service-order.ts
  src/types/service-stats.ts
  src/utils/axios.ts
  yarn.lock
Labels: enhancement, improvement, FRONT-END

#158 Doc/129 caso de uso 03
  docs/estudo-de-caso-uc/caso-de-uso-03.md
Labels: product and project vision

#163 Doc/adicionando casos de uso
  docs/estudo-de-caso-uc/caso-de-uso-01.md
  docs/estudo-de-caso-uc/caso-de-uso-02.md
  docs/estudo-de-caso-uc/caso-de-uso-03.md
  docs/estudo-de-caso-uc/caso-de-uso-04.md
  docs/estudo-de-caso-uc/caso-de-uso-05.md
  docs/estudo-de-caso-uc/caso-de-uso-06.md
  docs/estudo-de-caso-uc/introducao.md
Labels: product and project vision

#164 docs: updating uc 4
  docs/estudo-de-caso-uc/caso-de-uso-04.md
Labels: product and project vision
